In [2]:
import numpy as np#numpy aslında karmaşık hesaplamaları yapan büyük verilerin işlenmesinde bize yardımcı olan bir kütüphane olarak düşünülebilir
dizi=[[1,2],[3,4]]
dizi1=np.array(dizi)
print(dizi)
print(dizi1)
#numpy dizilerle normal diziler arasındaki fark burada görünüyor
#aslında daha anlaşılır daha matemaatiksel hale sokmaya yarar gibi düşünülebilir

[[1, 2], [3, 4]]
[[1 2]
 [3 4]]


In [4]:
print(type(dizi))
print(type(dizi1))

<class 'list'>
<class 'numpy.ndarray'>


In [7]:
print(dizi1.ndim)#.ndim numpy dizinin boyutunu döndürür

2


In [8]:
print(dizi1.shape)#numpy dizisinin bize kaç satır ve sütundan oluştuğunu döndürür tuple olarak
print(type(dizi1.shape))

(2, 2)
<class 'tuple'>


In [14]:
dizi=[1,2,3,4,5,77,9,2,1,3,5,45,7,61,5]
dizi1=np.array(dizi)#diziyi istediğimiz şekilde yeniden boyutlandırıyo
print(dizi1.reshape(3,5))#burada diziyi yeniden yazdırmamızın sebebi aslında orijinal diziyi değiştirmediğini göstermektir
print(dizi1)
print(dizi1.reshape(5,3))

[[ 1  2  3  4  5]
 [77  9  2  1  3]
 [ 5 45  7 61  5]]
[ 1  2  3  4  5 77  9  2  1  3  5 45  7 61  5]
[[ 1  2  3]
 [ 4  5 77]
 [ 9  2  1]
 [ 3  5 45]
 [ 7 61  5]]


In [16]:
dizi1=np.arange(0,100,5)#burada aslında bize bir numpy dizi döndürür
print(dizi1)
print(dizi1.reshape(5,4))

[ 0  5 10 15 20 25 30 35 40 45 50 55 60 65 70 75 80 85 90 95]
[[ 0  5 10 15]
 [20 25 30 35]
 [40 45 50 55]
 [60 65 70 75]
 [80 85 90 95]]


In [19]:
dizi1=dizi1.reshape(5,4)
ilksatir=dizi1[0:3]#dizinin istediğimiz satırını elde ediyoruz
print(ilksatir)

[[ 0  5 10 15]
 [20 25 30 35]
 [40 45 50 55]]


In [20]:
dizi1=dizi1.reshape(5,4)
ilksutun=dizi1[:,0:3]#dizinin tüm satırlarını alıp istediğimiz kadar sütununu alıyoruz
print(ilksutun)

[[ 0  5 10]
 [20 25 30]
 [40 45 50]
 [60 65 70]
 [80 85 90]]


In [21]:
print(dizi1[::-1])#diziyi ters çevirdik

[[80 85 90 95]
 [60 65 70 75]
 [40 45 50 55]
 [20 25 30 35]
 [ 0  5 10 15]]
